### ISSUE TITLE
Processing trajecory without momenta 

### ISSUE THREAD

**Issue by supers1x** [lorenzo-rovigatti/baggianalysis#5]
Something went wrong calculating MSD on a trajectory produced with `trajectory_print_momenta = false` in oxDNA input file.

```
Traceback (most recent call last):
  File "~/msd.py", line 11, in <module>
    msd_obs.analyse_and_print(trajectory, "msd.dat")
MemoryError: std::bad_alloc
```

**Comment by lorenzo-rovigatti** [comment]
Hi! I have committed a fix, let me know if it works also in your case.

**Comment by supers1x** [comment]
Thanks for the effort!
It works with line 92 in `OxDNAParser.cpp`  changed to `if(split.size() > 10) `, since the end of line is followed by a white space.
